services:
  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    # environment:
    #   - API_URL=https://api.example.com
    #   - CLIENT_URL=https://client.example.com
    volumes:
      - prometheus_data:/prometheus

volumes:
  prometheus_data: